### ISSUE TITLE
Is it possible to make it fill the whole site?

### ISSUE THREAD

**Issue by Developer-Mike** [ShatteredDisk/rickroll#1]

**Comment by ShatteredDisk** [comment]
I could try updating the resolution of the video. I'm slightly busy right now so I'll try to do it later tonight.

**Comment by ShatteredDisk** [comment]
just updated resolution, testing now...

**Comment by ShatteredDisk** [comment]
Ok, so it fills the whole of my screen, but I don't have a very large screen or monitor so try it yourself. (Seems to be updated to the largest resolution, closing this issue.)
