### ISSUE TITLE
Full length video?

### ISSUE THREAD

**Issue by mpatton125** [ShatteredDisk/rickroll#4]
Hey there - love the roll.  Any chance you could update to the full vid?  This one only goes for 2m 50s.

**Comment by VillainsRule4000** [comment]
Github requires that the video be under a certain size. This is probably the reason.

**Comment by ShatteredDisk** [comment]
So sorry I didn’t see this until now

**Comment by ShatteredDisk** [comment]
But yes, the video needs to be shorted so that it loads fast enough on slow devices and is under the CDN limit

**Comment by ShatteredDisk** [comment]
FYI issue #1 asked for it to fill the whole site and so time was traded for more quality
