### ISSUE TITLE
[Not Issue] Example Rickroll Implementation on Site

### ISSUE THREAD

**Issue by huang245** [ShatteredDisk/rickroll#5]
if you guys want see thousands of comment people being rickrolled by video from this project
[https://animixplay.to/v1/no-game-no-life-season-2](https://animixplay.to/v1/no-game-no-life-season-2)
580k people viewed until now

**Comment by ShatteredDisk** [comment]
nice

**Comment by ShatteredDisk** [comment]
I’m gonna close this issue to keep the inbox empty but I’ll pin it

**Comment by VillainsRule4000** [comment]
@ShatteredDisk I use your repository as an alternative to Youtube, since Youtube will not embed in sites.
