### ISSUE TITLE
Website without redirecting

### ISSUE THREAD

**Issue by something0000** [ShatteredDisk/rickroll#7]
Hey, how can I implement a site without redirecting it to `xxx.github.io/rickroll.mp4`?. So it will be just `xxx.github.io`

**Comment by ShatteredDisk** [comment]
I'm unfortunately not sure how to do this as embedding the video stops a lot of browsers and devices from autoplaying it (even with the attribute specified).

If you (or anyone else reading this) know/s how to do this, please let me know and I'll update the site.
